version: '3'
services:
  databases:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=xyz
      - MYSQL_DATABASE=xyz
      - MYSQL_USER=xyz
      - MYSQL_PASSWORD=xyz
  web:
    image: nginx
    ports:
      - "80:80"


    