version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      - wordpress_db_host=db:3306
      - wordpress_db_password=xyz
    volumes:
      - wordpress_data
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes: 
      - wordpress_data=/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=xyz
      - MYSQL_DATABASE=xyz
      - MYSQL_USER=xyz
      - MYSQL_PASSWORD=xyz
    
    
