version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_PASSWORD=123
      - WORDPRESS_USER=ninja
    volumes:
      - wordpress_data
  db:
    image: mysql:5.7
    volumes:
      - wordpress_data=/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=data
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=123



