version: '3'
services:
  databases:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=redhat
      - MYSQL_DATABASE=nginxdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123
  web:
    image: nginx
    ports:
      - "8888:80"
    depends_on:
      - databases      
